import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      'acdn-us.mitiendanube.com',
      'tiendadiggit.com.ar',
      'aws-obg-image-lb-2.tcl.com',
      'assets.bosecreative.com',
      'row.hyperx.com',
      'dcdn-us.mitiendanube.com',
      'http2.mlstatic.com',
      'resizer.glanacion.com',
      'm.media-amazon.com',
      'www.nikon.com.ar',
      'www.cordobadigital.net',
      'corrientesbikes.com.ar',
      'acdn-us.mitiendanube.com',
      'tienda.ohmyshop.com.ar',
      'rossellimac.es',
      'www.natcam.com',
      'gsmpro.com',
      'media.takealot.com',
      'images.fravega.com',
      'encrypted-tbn0.gstatic.com',
      'cellbell.in',
      'cdn.mos.cms.futurecdn.net',
      "www.comeros.com.ar",
      "heavenstorage.blob.core.windows.net",
      "img.global.news.samsung.com",
      "bioscomputacion.com.ar",
      "www.stockcenter.com.ar",
      "sportline.vtexassets.com",
      "es.dreamstime.com",
      "www.0800donrouch.com.ar",
      "shop.el-tasador.com.ar",
      "cdn-images.farfetch-contents.com",
      "cdn-media.glamira.com",
       "www.dexter.com.ar",
       "infinit.la",
       "eve.us-east-1.linodeobjects.com",
       "quebazar.com.ar",
       "kanji.com.ar",
       "los40.com",
       "www.ventasrosario.com.ar",
        "production.cdn.vaypol.com",
        "www.lg.com",
        "www.mycompanero.com",
         "whirlpoolargio.vtexassets.com",
         "www.mercadolibre.com.ar",
         "www.novogar.com.ar",
         "static.hendel.com"
      
    ],
  },
};

export default nextConfig;
